// samples/angular-todo/src/app/utilities/back-home/back-home.component.ts
/*
 * angular-todo-prototype
 *
 * back-home.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';

/**
 * Used to provide a link to take the user to the root of the application
 */
@Component({
  selector: 'app-back-home',
  templateUrl: './back-home.component.html',
})
export class BackHomeComponent {}

<!--
angular-todo-prototype

back-home.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<a
  class="cstm_back-home btn btn-sm text-bold text-decoration-none d-inline-block fs-6 my-2"
  [routerLink]="'/home'"
>
  <app-left-arrow-icon size="24px"></app-left-arrow-icon> Home
</a>

// samples/reactjs-todo/client/components/utilities/back-home.js
/*
 * forgerock-sample-web-react
 *
 * back-home.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';
import { Link } from 'react-router-dom';

import { AppContext } from '../../global-state';
import LeftArrowIcon from '../icons/left-arrow-icon';

export default function BackHome() {
  const [state] = useContext(AppContext);
  const bootstrapClasses =
    'btn btn-sm text-bold text-decoration-none d-inline-block fs-6 my-2';

  return (
    <Link
      className={`cstm_back-home ${bootstrapClasses} ${
        state.theme.mode === 'dark' ? 'cstm_back-home_dark' : ''
      }`}
      to="/"
    >
      <LeftArrowIcon />
      Home
    </Link>
  );
}
