// samples/reactjs-todo/client/components/journey/terms-conditions.js
/*
 * forgerock-sample-web-react
 *
 * terms-conditions.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React from 'react';

import { DEBUGGER } from '../../constants';

/**
 * @function TermsConditions - React component used for displaying terms and conditions
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.callback - The callback object from AM
 * @returns {Object} - React component object
 */
export default function TermsConditions({ callback, inputName }) {
  /** *************************************************************************
   * SDK INTEGRATION POINT
   * Summary: SDK callback methods for getting values
   * --------------------------------------------------------------------------
   * Details: Each callback is wrapped by the SDK to provide helper methods
   * for accessing values from the callbacks received from AM
   ************************************************************************* */
  if (DEBUGGER) debugger;
  const terms = callback.getTerms();
  const termsStart = terms.substring(0, 35) + ' ...';

  function setValue(e) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setAccepted(e.target.checked);
  }

  return (
    <div className="form-check mb-4">
      <input
        className="form-check-input"
        defaultChecked={false}
        id={inputName}
        onChange={setValue}
        type="checkbox"
      />
      <label htmlFor={inputName} className="form-check-label">
        Please accept our below Terms and Conditions
        <details>
          <summary className="fw-bold ps-1">{termsStart}</summary>
          {terms}
        </details>
      </label>
    </div>
  );
}

// samples/angular-todo/src/app/features/journey/terms-conditions/terms-conditions.component.ts
/*
 * angular-todo-prototype
 *
 * terms-conditions.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';
import { TermsAndConditionsCallback } from '@forgerock/javascript-sdk';

/**
 * Used to display terms and conditions, and collect the user's acceptance
 */
@Component({
  selector: 'app-terms-conditions',
  templateUrl: './terms-conditions.component.html',
})
export class TermsConditionsComponent {
  /**
   * The callback to be represented as terms and conditions
   */
  @Input() callback?: TermsAndConditionsCallback;

  /**
   * The name of the callback
   */
  @Input() name?: string;

  /**
   * Emits a boolean representing the updated state of the checkbox
   */
  @Output() updatedCallback = new EventEmitter<boolean>();

  /**
   * Emit an event to the parent component, passing the acceptance of the terms and conditions
   * @param event - the acceptance of the terms and conditions
   */
  updateValue(event: any): void {
    this.updatedCallback.emit(event.target.checked);
  }
}

<!--
angular-todo-prototype

terms-conditions.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="form-check mb-4">
  <input
    class="form-check-input"
    defaultChecked="false"
    [id]="name"
    (input)="updateValue($event)"
    type="checkbox"
  />
  <label [for]="name" class="form-check-label">
    Please accept our below Terms and Conditions
    <details>
      <!--
        Display a preview of the terms and conditions until the user expands the view
      -->
      <!--
        ****************************************************************************
        * SDK INTEGRATION POINT
        * Summary: SDK callback methods for getting values
        * --------------------------------------------------------------------------
        * Details: Each callback is wrapped by the SDK to provide helper methods
        * for accessing values from the callbacks received from AM
        ****************************************************************************
      -->
      <summary class="fw-bold ps-1">
        {{ callback?.getTerms()?.substring(0, 35) + ' ...' }}
      </summary>
      {{ callback?.getTerms() }}
    </details>
  </label>
</div>
