// samples/angular-todo/src/app/features/journey/form/form.component.ts
/*
 * angular-todo-prototype
 *
 * form.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import type { OnInit } from '@angular/core';
import { Component, Input } from '@angular/core';
import type { Router } from '@angular/router';
import { environment } from '../../../../environments/environment';
import type {
  FRLoginFailure,
  FRLoginSuccess,
  FRStep,
} from '@forgerock/javascript-sdk';
import { FRAuth, TokenManager, UserManager } from '@forgerock/javascript-sdk';
import type { UserService } from '../../../services/user.service';

/**
 * Used to display a login / registration form to the user, with authentication callbacks dynamically rendered based on the tree / journey
 */
@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
})
export class FormComponent implements OnInit {
  /**
   * The value representing whether this is a login or registration journey, or something else
   */
  @Input() action?: string;

  /**
   * The current step awaiting user input and submission to AM
   */
  step?: FRStep;

  /**
   * A representation of an authentication failure received from AM
   */
  failure?: FRLoginFailure;

  /**
   * A representation of an authentication success received from AM
   */
  success?: FRLoginSuccess;

  /**
   * The form title
   */
  title?: string;

  /**
   * The text for the submit button
   */
  buttonText?: string;

  /**
   * If the form is currently being submitted we want to display a spinner on the submit button
   */
  submittingForm = false;

  /**
   * The authentication tree or journey being specified in this authentication attempt
   */
  tree?: string;

  constructor(private router: Router, public userService: UserService) {}

  ngOnInit(): void {
    this.setConfigForAction(this.action);
    this.nextStep();
  }

  /**
   * Call AM with a previous step to get a new step
   * @param step - The previous step that should contain the input for AM
   */
  async nextStep(step?: FRStep): Promise<void> {
    this.submittingForm = true;

    try {
      /** *********************************************************************
       * SDK INTEGRATION POINT
       * Summary: Call the SDK's next method to submit the current step.
       * ----------------------------------------------------------------------
       * Details: This calls the next method with the previous step, expecting
       * the next step to be returned, or a success or failure.
       ********************************************************************* */
      const nextStep = await FRAuth.next(step, { tree: this.tree });

      /** *******************************************************************
       * SDK INTEGRATION POINT
       * Summary: Handle step based on step type
       * --------------------------------------------------------------------
       * Details: Determine whether the step is a login failure, success or
       * next step in the authentication journey, and handle appropriately.
       ******************************************************************* */
      switch (nextStep.type) {
        case 'LoginFailure':
          this.handleFailure(nextStep);
          break;
        case 'LoginSuccess':
          this.handleSuccess(nextStep);
          break;
        case 'Step':
          this.handleStep(nextStep);
          break;
        default:
          this.handleFailure();
      }
    } catch (err) {
      console.log(err);
    } finally {
      this.submittingForm = false;
    }
  }

  handleFailure(failure?: FRLoginFailure) {
    this.failure = failure;
  }

  /**
   * If the user authenticates successfully, update the UI to show a spinner, get an access token save user info then navigate home
   * @param success - The step representing authentication success
   */
  async handleSuccess(success?: FRLoginSuccess) {
    this.success = success;

    try {
      /** *********************************************************************
       * SDK INTEGRATION POINT
       * Summary: Get OAuth/OIDC tokens with Authorization Code Flow w/PKCE.
       * ----------------------------------------------------------------------
       * Details: Since we have successfully authenticated the user, we can now
       * get the OAuth2/OIDC tokens. We are passing the `forceRenew` option to
       * ensure we get fresh tokens, regardless of existing tokens.
       ************************************************************************* */
      await TokenManager.getTokens({ forceRenew: true });

      /** *********************************************************************
       * SDK INTEGRATION POINT
       * Summary: Call the user info endpoint for some basic user data.
       * ----------------------------------------------------------------------
       * Details: This is an OAuth2 call that returns user information with a
       * valid access token. This is optional and only used for displaying
       * user info in the UI.
       ********************************************************************* */
      const info = await UserManager.getCurrentUser();
      this.userService.info = info;
      this.userService.isAuthenticated = true;

      this.router.navigateByUrl('/');
    } catch (err) {
      console.error(err);
    }
  }

  /**
   * Store the next step in the authentication journey and set configuration depending on the action type
   * @param step - The next step in the journey
   */
  handleStep(step?: FRStep) {
    this.step = step;

    this.setConfigForAction(this.action);

    if (step?.getHeader()) {
      this.title = step?.getHeader();
    }
  }

  /**
   * Initialise configuration for the page based on whether this is a login or registration journey, or something else
   * @param action - The type of action this form is being used for
   */
  setConfigForAction(action?: string) {
    switch (action) {
      case 'login': {
        this.title = 'Sign In';
        this.buttonText = 'Sign In';
        this.tree = environment.JOURNEY_LOGIN;
        break;
      }
      case 'register': {
        this.title = 'Sign Up';
        (this.buttonText = 'Register'),
          (this.tree = environment.JOURNEY_REGISTER);
        break;
      }
      default: {
        this.title = 'Welcome';
        this.buttonText = 'Next';
        this.tree = environment.JOURNEY_LOGIN;
        break;
      }
    }
  }
}

<!--
angular-todo-prototype

form.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<!--
  Render conditions for presenting appropriate views to user.
  First, we need to handle no "step", which means we are waiting for the initial response from AM for authentication.
  Once we have a step, we then need to ensure we don't already have a success or failure. If we have a step but don't have a success or failure, we will likely have callbacks that we will need to present to the user in their render component form.
-->
<ng-container
  [ngTemplateOutlet]="
    success
      ? successMessage
      : failure
      ? failureMessage
      : showWebAuthn
      ? webAuthn
      : step
      ? callbacks
      : loading
  "
>
  <ng-template #loading>
    <!--
      Since there is no step information we need to call AM to retrieve the instructions for rendering the login form.
    -->
    <app-loading [message]="'Checking your session ...'"></app-loading>
  </ng-template>

  <ng-template #successMessage>
    <!--
      Since we have successfully authenticated, show a success message to user while we complete the process and redirect to home page.
    -->
    <app-loading [message]="'Success! Redirecting ...'"></app-loading>
  </ng-template>

  <ng-template #failureMessage>
    <!--
      We have failed to authenticate, show a failure message to the user.
    -->
    <app-alert [message]="failure?.getMessage()" [type]="'error'"></app-alert>
  </ng-template>

  <ng-template #webAuthn>
    <div>
      <app-webAuthn [webAuthnType]="webAuthnType" [step]="step"></app-webAuthn>
    </div>
  </ng-template>

  <ng-template #callbacks>
    <!--
     The step to render has callbacks, so we need to collect additional data from user. Show a form for the callbacks in this step.
    -->
    <div>
      <h1 class="text-center fs-2 mb-3" *ngIf="title">{{ title }}</h1>
      <div id="callbacks">
        <form #callbackForm (ngSubmit)="nextStep(step)" ngNativeValidate class="cstm_form">
          <!--
            Iterate through callbacks received from AM and invoke the callback to the appropriate callback component.
            The input to each component will be the callback and callback name, and the outputs will be the events emitted by the component.
            Events emitted by each component are handled by an expression mapping them to SDK functions, e.g. to set the password on the callback using the emitted value.
          -->
          <div *ngFor="let callback of step?.callbacks" v-bind:key="callback.payload._id">
            <!--
            ************************************************************************
            * SDK INTEGRATION POINT
            * Summary:SDK callback method for getting the callback type
            * ----------------------------------------------------------------------
            * Details: This method is helpful in quickly identifying the callback
            * when iterating through an unknown list of AM callbacks
            ************************************************************************
            -->

            <container-element [ngSwitch]="callback.getType()">
              <!--
                ***************************************************************************
                * SDK INTEGRATION POINT
                * Summary: SDK callback methods for setting values
                * ------------------------------------------------------------------------
                * Details: Each callback is wrapped by the SDK to provide helper methods
                * for writing values to the callbacks received from AM
                ***************************************************************************
              -->

              <!--
                Any callbacks of type NameCallback, ValidatedCreateUsernameCallback, and StringAttributeInputCallback can all be handled by the Text component.
              -->
              <app-text
                *ngSwitchCase="'NameCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setName($event)"
              ></app-text>
              <app-text
                *ngSwitchCase="'ValidatedCreateUsernameCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setName($event)"
              ></app-text>
              <app-text
                *ngSwitchCase="'StringAttributeInputCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setValue($event)"
              ></app-text>

              <!--
                Any callbacks of type PasswordCallback or ValidatedCreatePasswordCallback can all be handled by the Text component
              -->
              <app-password
                *ngSwitchCase="'PasswordCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setPassword($event)"
              ></app-password>
              <app-password
                *ngSwitchCase="'ValidatedCreatePasswordCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setPassword($event)"
              ></app-password>

              <!--
                Handle a BooleanAttributeInputCallback using the Boolean component.
              -->
              <app-boolean
                *ngSwitchCase="'BooleanAttributeInputCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setValue($event)"
              ></app-boolean>

              <!--
                Handle a ChoiceCallback using the Choice component.
              -->
              <app-choice
                *ngSwitchCase="'ChoiceCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setChoiceValue($event)"
              ></app-choice>

              <!--
                Handle a TermsAndConditionsCallback using the TermsConditions component.
              -->
              <app-terms-conditions
                *ngSwitchCase="'TermsAndConditionsCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setAccepted($event)"
              ></app-terms-conditions>

              <!--
                Handle a KbaCreateCallback using the Kba component.
                Emitted questions and answers are used to set the values on the callback.
              -->
              <app-kba
                *ngSwitchCase="'KbaCreateCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (setQuestion)="$any(callback).setQuestion($event)"
                (setAnswer)="$any(callback).setAnswer($event)"
              ></app-kba>

              <!--
                Handle a SelectIdPCallback using the identityProvider component.
              -->
              <app-identity-provider
                *ngSwitchCase="'SelectIdPCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setProvider($event)"
              >
              </app-identity-provider>

              <!--
                Handle a TextOutputCallback using the textOutput component.
              -->
              <app-textOutput *ngSwitchCase="'TextOutputCallback'"> </app-textOutput>

              <!--
                Handle a ConfirmationCallback using the confirmation component.
              -->
              <app-confirmation
                *ngSwitchCase="'ConfirmationCallback'"
                [callback]="$any(callback)"
                [name]="callback?.payload?.input?.[0]?.name"
                (updatedCallback)="$any(callback).setOptionValue($event)"
              >
              </app-confirmation>

              <!--
                Handle a RedirectCallback using the loading component.
                Emitted questions and answers are used to set the values on the callback.
              -->
              <app-loading
                *ngSwitchCase="'RedirectCallback'"
                [message]="'Redirecting ...'"
              ></app-loading>

              <!--
                 If current callback is not supported, render a warning message
              -->
              <app-unknown *ngSwitchDefault [callback]="callback"></app-unknown>
            </container-element>
          </div>
          <!--
            Show a button to submit the form
          -->
          <app-button [buttonText]="buttonText" [submittingForm]="submittingForm"></app-button>
        </form>
      </div>
    </div>
  </ng-template>
</ng-container>

// samples/reactjs-todo/client/components/journey/form.js
/*
 * forgerock-sample-web-react
 *
 * form.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { Fragment, useEffect, useContext, useReducer } from 'react';
import { useNavigate } from 'react-router-dom';

import Boolean from './boolean';
import { DEBUGGER } from '../../constants';
import Alert from './alert';
import Choice from './choice';
import Kba from './kba';
import Loading from '../utilities/loading';
import Password from './password';
import treeReducer from './tree-reducer';
import useJourneyHandler from './journey-state';
import { AppContext } from '../../global-state';
import TermsConditions from './terms-conditions';
import Text from './text';
import Unknown from './unknown';
import Button from './button';

/**
 * @function Form - React component for managing the user authentication journey
 * @param {Object} props - props object from React
 * @param {Object} props.action - Action object for a "reducer" pattern
 * @param {string} props.action.type - Action type string that represents the action
 * @param {Object} props.followUp - A function that should be run after successful authentication
 * @returns {Object} - React component object
 */
export default function Form({ action, bottomMessage, followUp, topMessage }) {
  /**
   * Compose the state used in this view.
   * First, we will use the global state methods found in the App Context.
   * Then, we will create local state to manage the login journey.
   *
   * The destructing of the hook's array results in index 0 having the state value,
   * and index 1 having the "setter" method to set new state values.
   */
  // Used for setting global authentication state
  const [state, methods] = useContext(AppContext);
  // Map action to form metadata: title, button text and tree
  const [form] = useReducer(treeReducer, treeReducer(null, action));
  // Used for redirection after success
  const navigate = useNavigate();

  /**
   * Custom "hook" for handling form orchestration
   */
  const [
    { formFailureMessage, renderStep, submittingForm, user },
    { setSubmissionStep, setSubmittingForm },
  ] = useJourneyHandler({ action, form });

  /**
   * If the user successfully authenticates, let React complete
   * rendering, then complete setting the state and redirect to home.
   */
  useEffect(() => {
    async function finalizeAuthState() {
      /**
       * First, let's see if we get a user back from useJourneyHandler.
       * If we do, let's set the user data and redirect back to home.
       */
      if (user) {
        /**
         * Set user state/info on "global state"
         */
        methods.setUser(user.name);
        methods.setEmail(user.email);
        methods.setAuthentication(true);

        // Run follow-up function if present
        followUp && (await followUp());

        // Redirect back to the home page
        navigate('/');
      }
    }

    finalizeAuthState();

    // Only `user` is a needed dependency, all others are "stable"
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user]);

  /**
   * Iterate through callbacks received from AM and map the callback to the
   * appropriate callback component, pushing that component
   * the StepComponent's array.
   */
  function mapCallbacksToComponents(cb, idx) {
    const name = cb?.payload?.input?.[0].name;
    /** *********************************************************************
     * SDK INTEGRATION POINT
     * Summary:SDK callback method for getting the callback type
     * ----------------------------------------------------------------------
     * Details: This method is helpful in quickly identifying the callback
     * when iterating through an unknown list of AM callbacks
     ********************************************************************* */
    if (DEBUGGER) debugger;
    switch (cb.getType()) {
      case 'ChoiceCallback':
        return <Choice callback={cb} inputName={name} key={name} />;
      case 'NameCallback':
      case 'ValidatedCreateUsernameCallback':
      case 'StringAttributeInputCallback':
        return <Text callback={cb} inputName={name} key={name} />;
      case 'PasswordCallback':
      case 'ValidatedCreatePasswordCallback':
        return <Password callback={cb} inputName={name} key={name} />;
      case 'BooleanAttributeInputCallback':
        return <Boolean callback={cb} inputName={name} key={name} />;
      case 'TermsAndConditionsCallback':
        return <TermsConditions callback={cb} inputName={name} key={name} />;
      case 'KbaCreateCallback':
        return <Kba callback={cb} inputName={name} key={name} />;
      default:
        // If current callback is not supported, render a warning message
        return <Unknown callback={cb} key={`unknown-${idx}`} />;
    }
  }

  /**
   * Render conditions for presenting appropriate views to user.
   * First, we need to handle no "step", which means we are waiting for
   * the initial response from AM for authentication.
   *
   * Once we have a step, we then need to ensure we don't already have a
   * success or failure. If we have a step but don't have a success or
   * failure, we will likely have callbacks that we will need to present'
   * to the user in their render component form.
   */
  if (!renderStep) {
    /**
     * Since there is no step information we need to call AM to retrieve the
     * instructions for rendering the login form.
     */
    return <Loading message="Checking your session ..." />;
  } else if (renderStep.type === 'LoginSuccess') {
    /**
     * Since we have successfully authenticated, show a success message to
     * user while we complete the process and redirect to home page.
     */
    return <Loading message="Success! Redirecting ..." />;
  } else if (renderStep.type === 'Step') {
    /**
     * The step to render has callbacks, so we need to collect additional
     * data from user. Map callbacks to form inputs.
     */
    return (
      <Fragment>
        <h1 className={`text-center fs-2 mb-3 ${state.theme.textClass}`}>
          {form.titleText}
        </h1>
        {topMessage}
        <form
          className="cstm_form"
          onSubmit={(event) => {
            event.preventDefault();
            // Indicate form processing
            setSubmittingForm(true);
            // set currently rendered step as step to be submitted
            setSubmissionStep(renderStep);
          }}
        >
          {formFailureMessage ? (
            <Alert message={formFailureMessage} type="error" />
          ) : null}
          {
            /**
             * Map over the callbacks in renderStep and render the appropriate
             * component for each one.
             */
            renderStep.callbacks.map(mapCallbacksToComponents)
          }
          <Button
            buttonText={form.buttonText}
            submittingForm={submittingForm}
          />
        </form>
        {bottomMessage}
      </Fragment>
    );
  } else {
    /**
     * Just in case things blow up.
     */
    return <Alert message={renderStep.payload.message} type="error" />;
  }
}
