// samples/angular-todo/src/app/features/journey/kba/kba.component.ts
/*
 * angular-todo-prototype
 *
 * kba.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, EventEmitter, Input, Output } from '@angular/core';
import type { KbaCreateCallback } from '@forgerock/javascript-sdk';

/**
 * Used to display a KBA security question
 */
@Component({
  selector: 'app-kba',
  templateUrl: './kba.component.html',
})
export class KbaComponent {
  /**
   * The callback to be represented as a KBA security question
   */
  @Input() callback?: KbaCreateCallback;

  /**
   * The name of the callback
   */
  @Input() name?: string;

  /**
   * Emits a string representing the selected question
   */
  @Output() setQuestion = new EventEmitter<string>();

  /**
   * Emits a string representing the answer entered
   */
  @Output() setAnswer = new EventEmitter<string>();

  /**
   * Emit an event to the parent component, passing the selected question
   * @param event - the question
   */
  questionSet(event: any): void {
    this.setQuestion.emit(event.target.value);
  }

  /**
   * Emit an event to the parent component, passing the answer entered
   * @param event - the answer
   */
  answerSet(event: any): void {
    this.setAnswer.emit(event.target.value);
  }
}

<!--
angular-todo-prototype

kba.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div>
  <hr class="cstm_hr d-flex mt-5" />
  <div class="cstm_hr-lock_light d-flex justify-content-center">
    <app-lock-icon></app-lock-icon>
  </div>
  <h2 class="fs-6 mt-5 fw-normal">
    Provide security question(s) & answer(s) below
  </h2>
  <div class="cstm_form-floating form-floating mb-3">
    <select
      class="cstm_form-select form-select bg-transparent"
      [id]="name"
      [name]="name"
      (input)="questionSet($event)"
      required="true"
    >
      <option value="">No selection</option>

      <!--
        ****************************************************************************
        * SDK INTEGRATION POINT
        * Summary: SDK callback methods for getting values
        * --------------------------------------------------------------------------
        * Details: Each callback is wrapped by the SDK to provide helper methods
        * for accessing values from the callbacks received from AM
        ****************************************************************************
      -->
      <option
        *ngFor="let question of callback?.getPredefinedQuestions()"
        v-bind:key="question"
        [selected]="callback?.payload?.input?.[0]?.value === question"
      >
        {{ question }}
      </option>
    </select>
    <label [for]="name">{{ callback?.getPrompt() }}</label>
  </div>
  <div class="cstm_form-floating form-floating pb-5 mb-5 border-bottom pb-3">
    <!--
      ****************************************************************************
      * SDK INTEGRATION POINT
      * Summary: SDK callback methods for getting values
      * --------------------------------------------------------------------------
      * Details: Each callback is wrapped by the SDK to provide helper methods
      * for accessing values from the callbacks received from AM
      ****************************************************************************
    -->
    <input
      class="cstm_form-control form-control bg-transparent"
      [id]="callback?.payload?.input?.[1]?.name"
      [name]="callback?.payload?.input?.[1]?.name"
      (input)="answerSet($event)"
      placeholder="Security Answer"
      required="true"
      type="text"
      [defaultValue]="callback?.payload?.input?.[1]?.value"
    />
    <label [for]="callback?.payload?.input?.[1]?.name">Security Answer</label>
  </div>
</div>

// samples/reactjs-todo/client/components/journey/kba.js
/*
 * forgerock-sample-web-react
 *
 * kba.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { Fragment, useContext } from 'react';

import { DEBUGGER } from '../../constants';
import { AppContext } from '../../global-state';
import LockIcon from '../icons/lock-icon';

/**
 * @function Kba - React component used for displaying KBA security question
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.callback - The callback object from AM
 * @returns {Object} - React component object
 */
export default function Kba({ callback, inputName }) {
  const [state] = useContext(AppContext);

  /** *************************************************************************
   * SDK INTEGRATION POINT
   * Summary: SDK callback methods for getting values
   * --------------------------------------------------------------------------
   * Details: Each callback is wrapped by the SDK to provide helper methods
   * for accessing values from the callbacks received from AM
   ************************************************************************* */
  if (DEBUGGER) debugger;
  const prompt = callback.getPrompt();
  const questions = callback.getPredefinedQuestions();
  const inputNameQuestion = inputName;
  const inputNameAnswer = callback.payload.input[1].name;

  function setAnswer(e) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setAnswer(e.target.value);
  }

  function setQuestion(e) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setQuestion(e.target.value);
  }

  return (
    <Fragment>
      <hr className={`cstm_hr d-flex mt-5 ${state.theme.textClass}`} />
      <div className={`cstm_hr-lock_${state.theme.mode} d-flex justify-content-center`}>
        <LockIcon />
      </div>
      <h2 className={`fs-6 mt-5 fw-normal ${state.theme.textClass}`}>
        Provide security question(s) & answer(s) below
      </h2>
      <div className="cstm_form-floating form-floating mb-3">
        <select
          className={`cstm_form-select form-select bg-transparent ${state.theme.textClass} ${state.theme.borderClass}`}
          id={inputNameQuestion}
          name={inputNameQuestion}
          onChange={setQuestion}
          required={true}
        >
          <option value="">No selection</option>
          {questions.map((question, idx) => {
            return (
              <option key={idx} value={question}>
                {question}
              </option>
            );
          })}
        </select>
        <label htmlFor={inputNameQuestion}>{prompt}</label>
      </div>
      <div
        className={`cstm_form-floating form-floating pb-5 mb-5 border-bottom pb-3 ${
          state.theme.mode === 'dark' ? 'border-white' : 'border-secondary'
        }`}
      >
        <input
          className={`cstm_form-control form-control bg-transparent ${state.theme.textClass} ${state.theme.borderClass}`}
          id={inputNameAnswer}
          name={inputNameAnswer}
          onChange={setAnswer}
          placeholder="Security Answer"
          required={true}
          type="text"
        />
        <label htmlFor={inputNameAnswer}>Security Answer</label>
      </div>
    </Fragment>
  );
}
