// samples/angular-todo/src/app/features/journey/password/password.component.ts
/*
 * angular-todo-prototype
 *
 * password.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { PasswordCallback, ValidatedCreatePasswordCallback } from '@forgerock/javascript-sdk';

/**
 * Used to collect or set a password
 */
@Component({
  selector: 'app-password',
  templateUrl: './password.component.html',
})
export class PasswordComponent implements OnInit {
  /**
   * The callback to be represented as either a password challenge or password set field
   */
  @Input() callback?: PasswordCallback | ValidatedCreatePasswordCallback;

  /**
   * The name of the callback
   */
  @Input() name?: string;

  /**
   * Emits a string representing the password entered by the user
   */
  @Output() updatedCallback = new EventEmitter<string>();

  /**
   * Is password to be shown in clear text
   */
  isVisible = false;

  /**
   * Is the password a required field in the form
   */
  isRequired = false;

  /**
   * Validation error messages
   */
  failureMessages: string[] = [];

  /**
   * Initialise any failure messages and whether this field is mandatory
   */
  ngOnInit(): void {
    this.isRequired = this.getIsRequired(this.callback);
    this.failureMessages = this.evaluateFailedPolicies(this.callback);
  }

  /**
   * Emit an event to the parent component, passing the password entered
   * @param event - the value of the password field
   */
  updateValue(event: any): void {
    this.updatedCallback.emit(event.target.value);
  }

  /**
   * Toggle the password from masked to plaintext
   */
  toggleVisibility(): void {
    this.isVisible = !this.isVisible;
  }

  /**
   * Determines whether this field is mandatory
   * @param callback - the password callback to be evaluated
   * @returns boolean - is this field mandatory
   */
  getIsRequired(callback?: PasswordCallback | ValidatedCreatePasswordCallback): boolean {
    if (callback === undefined || callback instanceof PasswordCallback) return false;

    const policies = callback.getPolicies();

    if (policies.policyRequirements) {
      return policies.policyRequirements.includes('REQUIRED');
    } else if (callback?.isRequired) {
      return callback.isRequired();
    }

    return false;
  }

  /**
   * Process password policy feedback from AM
   * @param callback - the password callback to be evaluated
   * @returns string[] - an array of password policy failures
   */
  evaluateFailedPolicies(callback?: PasswordCallback | ValidatedCreatePasswordCallback): string[] {
    if (callback === undefined || callback instanceof PasswordCallback) return [];

    const failedPolicies = callback.getFailedPolicies();

    const validationFailures: string[] = [];

    failedPolicies.forEach((policy) => {
      const policyObj = JSON.parse(JSON.parse(JSON.stringify(policy)));

      console.log(policyObj.policyRequirement);

      switch (policyObj.policyRequirement) {
        case 'LENGTH_BASED':
          validationFailures.push(
            `Ensure password contains more than ${policyObj.params['min-password-length']} characters. `,
          );
          break;
        case 'CHARACTER_SET':
          validationFailures.push(
            `Ensure password contains 1 of each: capital letter, number and special character. `,
          );
          break;
        default:
          break;
      }
    });
    return validationFailures;
  }
}

<!--
angular-todo-prototype

password.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_form-floating input-group form-floating mb-3">
  <!--
    ****************************************************************************
    * SDK INTEGRATION POINT
    * Summary: SDK callback methods for getting values
    * --------------------------------------------------------------------------
    * Details: Each callback is wrapped by the SDK to provide helper methods
    * for accessing values from the callbacks received from AM
    ****************************************************************************
  -->
  <input
    class="cstm_form-control form-control bg-transparent"
    [ngClass]="{ 'is-invalid': failureMessages.length }"
    [id]="name"
    [name]="name"
    [placeholder]="callback?.getPrompt()"
    [required]="isRequired ? 'required' : ''"
    (input)="updateValue($event)"
    [type]="isVisible ? 'text' : 'password'"
  />
  <label [for]="name">{{ callback?.getPrompt() }}</label>
  <button
    class="cstm_input-icon border-start-0 input-group-text bg-transparent"
    (click)="toggleVisibility()"
    type="button"
  >
    <app-eye-icon [visible]="isVisible"></app-eye-icon>
  </button>

  <div
    *ngIf="failureMessages && failureMessages.length > 0"
    class="invalid-feedback"
  >
    <div *ngFor="let message of failureMessages">{{ message }}</div>
  </div>
</div>

// samples/reactjs-todo/client/components/journey/password.js
/*
 * forgerock-sample-web-react
 *
 * password.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext, useState } from 'react';

import { DEBUGGER } from '../../constants';
import { AppContext } from '../../global-state';
import EyeIcon from '../icons/eye-icon';

/**
 * @function Password - React component used for displaying password callback
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.callback - The callback object from AM
 * @param {string} props.errorMessage - Error message string
 * @returns {Object} - React component object
 */
export default function Password({ callback, errorMessage, inputName }) {
  const [state] = useContext(AppContext);

  /** *************************************************************************
   * SDK INTEGRATION POINT
   * Summary: SDK callback methods for getting values
   * --------------------------------------------------------------------------
   * Details: Each callback is wrapped by the SDK to provide helper methods
   * for accessing values from the callbacks received from AM
   ************************************************************************* */
  if (DEBUGGER) debugger;
  const failedPolicies =
    callback.getFailedPolicies && callback.getFailedPolicies();
  const passwordLabel = callback.getPrompt();
  const policies = callback.getPolicies && callback.getPolicies();
  const [isVisible, setVisibility] = useState(false);

  let Validation = null;

  let isRequired;
  let validationClass;

  /**
   * @function setValue - Sets the value on the callback on element blur (lose focus)
   * @param {Object} event
   */
  function setValue(event) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setPassword(event.target.value);
  }

  /**
   * @function toggleVisibility - toggles the password from masked to plaintext
   */
  function toggleVisibility() {
    setVisibility(!isVisible);
  }

  if (errorMessage) {
    validationClass = 'is-invalid';
    Validation = <div className="invalid-feedback">{errorMessage}</div>;
  }

  if (failedPolicies && failedPolicies.length) {
    const validationFailure = failedPolicies.reduce((prev, curr) => {
      let failureObj;
      try {
        failureObj = JSON.parse(curr);
      } catch (err) {
        console.log(`Parsing failure for ${passwordLabel}`);
      }

      switch (failureObj.policyRequirement) {
        case 'LENGTH_BASED':
          prev = `${prev}Ensure password contains more than ${failureObj.params['min-password-length']} characters. `;
          break;
        case 'CHARACTER_SET':
          prev = `${prev}Ensure password contains 1 of each: capital letter, number and special character. `;
          break;
        default:
          prev = `${prev}Please check this value for correctness.`;
      }
      return prev;
    }, '');
    validationClass = 'is-invalid';
    Validation = <div className="invalid-feedback">{validationFailure}</div>;
  }

  if (policies?.policyRequirements) {
    isRequired = policies.policyRequirements.includes('REQUIRED');
  } else if (callback.isRequired) {
    isRequired = callback.isRequired();
  }

  return (
    <div className="cstm_form-floating input-group form-floating mb-3">
      <input
        className={`cstm_input-password form-control ${
          validationClass ? validationClass : ''
        } border-end-0 bg-transparent ${state.theme.textClass} ${
          state.theme.borderClass
        }`}
        id={inputName}
        name={inputName}
        onChange={setValue}
        placeholder={passwordLabel}
        type={isVisible ? 'text' : 'password'}
        required={isRequired}
      />
      <label htmlFor={inputName}>{passwordLabel}</label>
      <button
        className={`cstm_input-icon border-start-0 input-group-text bg-transparent ${state.theme.textClass} ${state.theme.borderClass}`}
        onClick={toggleVisibility}
        type="button"
      >
        <EyeIcon visible={isVisible} />
      </button>
      {Validation}
    </div>
  );
}
