// samples/angular-todo/src/app/features/journey/text/text.component.ts
/*
 * angular-todo-prototype
 *
 * text.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import {
  AttributeInputCallback,
  NameCallback,
  ValidatedCreateUsernameCallback,
} from '@forgerock/javascript-sdk';

/**
 * Used to collect a username, email address or any other text
 */
@Component({
  selector: 'app-text',
  templateUrl: './text.component.html',
})
export class TextComponent implements OnInit {
  /**
   * The callback to be represented as a username, create username, or text input field
   */
  @Input() callback?:
    | NameCallback
    | ValidatedCreateUsernameCallback
    | AttributeInputCallback<string>;

  /**
   * The name of the callback
   */
  @Input() name?: string;

  /**
   * Emits a string representing the text entered by the user
   */
  @Output() updatedCallback = new EventEmitter<string>();

  /**
   * Is the text a required field in the form
   */
  isRequired: boolean = false;

  /**
   * Validation error messages
   */
  failureMessages: string[] = [];

  /**
   * Initialise any failure messages and whether this field is mandatory
   */
  ngOnInit(): void {
    this.isRequired = this.getIsRequired(this.callback);
    this.failureMessages = this.evaluateFailedPolicies(this.callback);
  }

  /**
   * Emit an event to the parent component, passing the text entered
   * @param event - the value of the text field
   */
  updateValue(event: any): void {
    this.updatedCallback.emit(event.target.value);
  }

  /**
   * Determines whether this field is mandatory
   * @param callback - the text callback to be evaluated
   * @returns boolean - is this field mandatory
   */
  getIsRequired(
    callback?:
      | NameCallback
      | ValidatedCreateUsernameCallback
      | AttributeInputCallback<string>
  ): boolean {
    if (
      callback === undefined ||
      callback instanceof NameCallback ||
      callback.getType() === 'NameCallback'
    )
      return false;

    const policies = callback.getPolicies();

    if (callback.getType() === 'ValidatedCreateUsernameCallback') {
      return policies.policyRequirements.includes('REQUIRED');
    } else {
      return callback.isRequired();
    }
  }

  /**
   * Process text policy feedback from AM
   * @param callback - the text callback to be evaluated
   * @returns string[] - an array of password policy failures
   */
  evaluateFailedPolicies(
    callback?:
      | NameCallback
      | ValidatedCreateUsernameCallback
      | AttributeInputCallback<string>
  ): string[] {
    if (
      callback === undefined ||
      callback instanceof NameCallback ||
      callback.getType() === 'NameCallback'
    )
      return [];

    const failedPolicies = callback.getFailedPolicies();

    const validationFailures: string[] = [];

    failedPolicies.forEach((policy) => {
      const policyObj = JSON.parse(JSON.parse(JSON.stringify(policy)));

      switch (policyObj.policyRequirement) {
        case 'VALID_USERNAME':
          validationFailures.push('Please choose a different username');
          break;
        case 'VALID_EMAIL_ADDRESS_FORMAT':
          validationFailures.push('Please use a valid email address');
          break;
        default:
          break;
      }
    });
    return validationFailures;
  }
}

<!--
angular-todo-prototype

text.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_form-floating form-floating mb-3">
  <!--
    ****************************************************************************
    * SDK INTEGRATION POINT
    * Summary: SDK callback methods for getting values
    * --------------------------------------------------------------------------
    * Details: Each callback is wrapped by the SDK to provide helper methods
    * for accessing values from the callbacks received from AM
    ****************************************************************************
  -->
  <input
    class="cstm_form-control form-control bg-transparent"
    [ngClass]="{ 'is-invalid': failureMessages.length }"
    [id]="name"
    [name]="name"
    [placeholder]="callback?.getPrompt()"
    [attr.required]="isRequired || null"
    (input)="updateValue($event)"
    [type]="
      callback?.getOutputByName('name', undefined) === 'mail' ? 'email' : 'text'
    "
    [defaultValue]="callback?.getInputValue()"
  />
  <label [for]="name">{{ callback?.getPrompt() }}</label>

  <div *ngIf="failureMessages" class="invalid-feedback">
    <div *ngFor="let message of failureMessages">{{ message }}</div>
  </div>
</div>

// samples/reactjs-todo/client/components/journey/text.js
/*
 * forgerock-sample-web-react
 *
 * text.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';

import { DEBUGGER } from '../../constants';
import { AppContext } from '../../global-state';

/**
 * @function Text- React component used for displaying text callback
 * @param {Object} props - React props object passed from parent
 * @param {Object} props.callback - The callback object from AM
 * @returns {Object} - React component object
 */
export default function Text({ callback, inputName }) {
  const [state] = useContext(AppContext);

  /** *************************************************************************
   * SDK INTEGRATION POINT
   * Summary: SDK callback methods for getting values
   * --------------------------------------------------------------------------
   * Details: Each callback is wrapped by the SDK to provide helper methods
   * for accessing values from the callbacks received from AM
   ************************************************************************* */
  if (DEBUGGER) debugger;
  const existingValue = callback.getInputValue();
  const failedPolicies =
    callback.getFailedPolicies && callback.getFailedPolicies();
  const policies = callback.getPolicies && callback.getPolicies();
  const textInputLabel = callback.getPrompt();
  const stringAttributeName = callback.getName && callback.getName();

  let isRequired;
  let Validation = null;
  let validationClass = '';

  /**
   * @function setValue - Sets the value on the callback on element blur (lose focus)
   * @param {Object} event
   */
  function setValue(event) {
    /** ***********************************************************************
     * SDK INTEGRATION POINT
     * Summary: SDK callback methods for setting values
     * ------------------------------------------------------------------------
     * Details: Each callback is wrapped by the SDK to provide helper methods
     * for writing values to the callbacks received from AM
     *********************************************************************** */
    if (DEBUGGER) debugger;
    callback.setInputValue(event.target.value);
  }

  if (failedPolicies?.length) {
    const validationFailure = failedPolicies.reduce((prev, failureObj) => {
      switch (failureObj.policyRequirement) {
        case 'VALID_USERNAME':
          prev = `${prev}Please choose a different username. `;
          break;
        case 'VALID_EMAIL_ADDRESS_FORMAT':
          prev = `${prev}Please use a valid email address. `;
          break;
        default:
          prev = `${prev}Please check this value for correctness.`;
      }
      return prev;
    }, '');
    validationClass = 'is-invalid';
    Validation = <div className="invalid-feedback">{validationFailure}</div>;
  }

  if (policies?.policyRequirements) {
    isRequired = policies.policyRequirements.includes('REQUIRED');
  } else if (callback.isRequired) {
    isRequired = callback.isRequired();
  }

  return (
    <div className={`cstm_form-floating form-floating mb-3`}>
      <input
        className={`cstm_form-control form-control ${validationClass} bg-transparent ${state.theme.textClass} ${state.theme.borderClass}`}
        defaultValue={existingValue}
        id={inputName}
        name={inputName}
        onChange={setValue}
        placeholder={textInputLabel}
        required={isRequired ? 'required' : ''}
        type={stringAttributeName == 'mail' ? 'email' : 'text'}
      />
      <label htmlFor={inputName}>{textInputLabel}</label>
      {Validation}
    </div>
  );
}
