// samples/reactjs-todo/client/components/layout/footer.js
/*
 * forgerock-sample-web-react
 *
 * footer.js
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import React, { useContext } from 'react';

import { AppContext } from '../../global-state';

/**
 * @function Footer - Footer React component
 * @returns {Object} - React component object
 */
export default function Footer() {
  const [state] = useContext(AppContext);

  return (
    <div className="cstm_container container-fluid">
      <small
        className={`border-top d-block mt-5 py-5 ${state.theme.textClass} ${state.theme.borderHighContrastClass}`}
      >
        The React name and logomark are properties of <a href="https://reactjs.org">Facebook</a>,
        and their use herein is for learning and illustrative purposes only.
      </small>
    </div>
  );
}

// samples/angular-todo/src/app/layout/footer/footer.component.ts
/*
 * angular-todo-prototype
 *
 * footer.component.ts
 *
 * Copyright (c) 2021 ForgeRock. All rights reserved.
 * This software may be modified and distributed under the terms
 * of the MIT license. See the LICENSE file for details.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
})
export class FooterComponent {}

<!--
angular-todo-prototype

footer.component.html

Copyright (c) 2021 ForgeRock. All rights reserved.
This software may be modified and distributed under the terms
of the MIT license. See the LICENSE file for details.
-->

<div class="cstm_container container-fluid">
  <small class="border-top d-block mt-5 py-5">
    The Angular name and logomark are properties of
    <a href="http://angular.io/license">Google LLC</a>, and their use herein is
    for learning and illustrative purposes only.
  </small>
</div>
